// Builds dist-offline/character-quest-test.html: one file with the whole app, server and database.
import * as esbuild from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const off = path.join(root, 'offline');
const migDir = path.join(root, 'server/migrations');
const migs = fs.readdirSync(migDir).filter((f) => f.endsWith('.sql')).sort();
fs.writeFileSync(path.join(off, 'migrations.gen.ts'), `// generated by build.mjs\nexport const MIGRATIONS: [string, string][] = ${JSON.stringify(migs.map((f) => [f, fs.readFileSync(path.join(migDir, f), 'utf8')]))};\n`);

const alias = {
  'express': path.join(off, 'express.ts'),
  'socket.io': path.join(off, 'socketio.ts'),
  'socket.io-client': path.join(off, 'socketio.ts'),
  'node:crypto': path.join(off, 'crypto.ts'),
  'dotenv/config': path.join(off, 'empty.ts'),
  '@cq/shared': path.join(root, 'shared/src/index.ts'),
  'bcryptjs': path.join(off, 'bcrypt.ts')
};
fs.writeFileSync(path.join(off, 'empty.ts'), 'export {};\n');
const plugin = {
  name: 'offline-alias',
  setup(b) {
    b.onResolve({ filter: /.*/ }, (a) => {
      if (alias[a.path] && !(a.path === 'bcryptjs' && a.importer.endsWith('bcrypt.ts'))) return { path: alias[a.path] };
      // The server's PostgreSQL pool becomes the in-browser database.
      if (/(^|\/)db\.js$/.test(a.path) && a.importer.includes(`${path.sep}server${path.sep}src`)) return { path: path.join(off, 'db.ts') };
      if (a.path === 'pg') return { path: path.join(off, 'empty.ts') };
      return undefined;
    });
  }
};
const out = await esbuild.build({
  entryPoints: [path.join(off, 'entry.ts')], bundle: true, format: 'esm', platform: 'browser', target: 'es2022', write: false, minify: true,
  outdir: path.join(root, 'dist-offline/tmp'), jsx: 'automatic', loader: { '.svg': 'dataurl', '.png': 'dataurl' },
  define: {
    __CQ_OFFLINE__: 'true', 'process.env.NODE_ENV': '"production"',
    'process.env': JSON.stringify({ NODE_ENV: 'production', SEED_DEMO: 'true', ADMIN_USERNAME: 'admin', ADMIN_PASSWORD: 'admin123', SESSION_SECRET: 'offline-test-build', TEACHER_SIGNUP_CODE: 'letmeteach', DATABASE_URL: 'pglite', PORT: '0', SESSION_DAYS: '30' })
  },
  plugins: [plugin], logLevel: 'warning'
});
const js = out.outputFiles.find((f) => f.path.endsWith('.js')).text;
const css = out.outputFiles.find((f) => f.path.endsWith('.css'))?.text ?? '';
const pgDir = path.join(root, 'node_modules/@electric-sql/pglite/dist');
const b64gz = (f) => zlib.gzipSync(fs.readFileSync(path.join(pgDir, f)), { level: 9 }).toString('base64');
const banner = `.offline-banner{position:fixed;left:10px;top:40%;z-index:100;display:flex;flex-direction:column;gap:8px;align-items:stretch;background:#1d2a6b;color:#fff;font:600 13px/1.3 system-ui,sans-serif;padding:10px 12px;border-radius:12px;width:230px;box-shadow:0 6px 20px rgba(0,0,0,.35)}
.offline-banner.collapsed{width:auto;padding:0;background:transparent;box-shadow:none}.offline-banner.collapsed>*:not([data-toggle]){display:none}
.offline-banner select,.offline-banner button{font:inherit;border-radius:8px;border:0;padding:5px 10px;background:#fff;color:#1d2a6b;cursor:pointer}
.offline-banner [data-toggle]{background:#1d2a6b;color:#fff;border:1px solid rgba(255,255,255,.4)}.offline-banner [data-reset]{background:#ffd166}.offline-banner label{display:flex;gap:6px;align-items:center;justify-content:space-between}
#cq-boot{position:fixed;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;background:#141a2e;color:#fff;font:600 16px system-ui,sans-serif;z-index:5}`;
const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Character Quest (offline test)</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@500;600;700&family=Nunito:wght@500;600;700;800&display=swap" rel="stylesheet">
<style>${css}\n${banner}</style></head>
<body><div id="root"><div id="cq-boot"><h2>Character Quest</h2><p id="cq-boot-status">Loading…</p></div></div>
<script id="cq-pg-wasm" type="application/octet-stream">${b64gz('pglite.wasm')}</script>
<script id="cq-pg-data" type="application/octet-stream">${b64gz('pglite.data')}</script>
<script type="module">${js.replace(/<\/script/gi, '<\\/script')}</script>
</body></html>`;
fs.mkdirSync(path.join(root, 'dist-offline'), { recursive: true });
const file = path.join(root, 'dist-offline/character-quest-test.html');
fs.writeFileSync(file, html);
console.log(`wrote ${file} (${(html.length / 1e6).toFixed(1)} MB)`);
